### ISSUE TITLE
Observable linebreak

### ISSUE THREAD

**Issue by birkir** [ueno-llc/styleguide#8]
Instead of hardcoding @observable, have the rule configurable with array of strings to enforce newline.

That way we can easily add more properties like `@computed`, `@action` and so on.

**Comment by jeremybarbet** [comment]
Actually, I gave a wrong name to the rule. It's should be called `decorator-line-break.js` Because it's checking for all decorators if they are not in the same line of theirs values and not only for the `@observable` decorator.

Does it make sense to give an array of value? if we want a line break after an `@observable` there is big chance we want the same linting for the others decorators, right?
